package storage

import (
	"encoding/json"



















































































































































































































































































































































































































































































































































}	}		t.Errorf("Expected 2, got %d", count)	if count != 2 {	count, _ = storage.BoardCount()	storage.SaveBoard(model.NewBoard("b2", "Board 2"))	storage.SaveBoard(model.NewBoard("b1", "Board 1"))	}		t.Errorf("Expected 0, got %d", count)	if count != 0 {	count, _ := storage.BoardCount()	storage, _ := NewStorageWithPath(dir)	defer cleanup()	dir, cleanup := createTestDir(t)func TestBoardCount(t *testing.T) {}	}		t.Error("Should have boards after saving")	if !has {	has, _ = storage.HasBoards()	storage.SaveBoard(board)	board := model.NewBoard("test", "Test")	}		t.Error("Should not have boards initially")	if has {	has, _ := storage.HasBoards()	storage, _ := NewStorageWithPath(dir)	defer cleanup()	dir, cleanup := createTestDir(t)func TestHasBoards(t *testing.T) {}	}		t.Errorf("Expected sanitized filename, got %s", path)	if path != "tsk-export-My-Test-Board.json" {	path := storage.DefaultExportPath(board)	board := model.NewBoard("test", "My Test Board")	storage, _ := NewStorageWithPath(dir)	defer cleanup()	dir, cleanup := createTestDir(t)func TestDefaultExportPath(t *testing.T) {}	}		t.Error("Importing invalid JSON should fail")	if err == nil {	_, err = storage.ImportBoard(invalidPath)	os.WriteFile(invalidPath, []byte("not json"), 0644)	invalidPath := filepath.Join(dir, "invalid.json")	// Invalid JSON	}		t.Error("Importing non-existent file should fail")	if err == nil {	_, err := storage.ImportBoard("/non/existent/path.json")	// Non-existent file	storage, _ := NewStorageWithPath(dir)	defer cleanup()	dir, cleanup := createTestDir(t)func TestImportBoardInvalidFile(t *testing.T) {}	}		t.Error("Saved board name mismatch")	if loaded.Name != imported.Name {	}		t.Fatalf("Imported board not saved: %v", err)	if err != nil {	loaded, err := storage.LoadBoard(imported.ID)	// Verify board was saved	}		t.Error("Imported task should have new ID")	if imported.Tasks[0].ID == "task-orig" {	}		t.Errorf("Expected 1 task, got %d", len(imported.Tasks))	if len(imported.Tasks) != 1 {	}		t.Errorf("Expected name with (imported) suffix, got %s", imported.Name)	if imported.Name != "Imported Board (imported)" {	}		t.Error("Imported board should have new ID")	if imported.ID == "original-id" {	// Verify new IDs were assigned	}		t.Fatalf("ImportBoard failed: %v", err)	if err != nil {	imported, err := storage.ImportBoard(importPath)	// Import it	os.WriteFile(importPath, data, 0644)	importPath := filepath.Join(dir, "import.json")	data, _ := json.MarshalIndent(exportBoard, "", "  ")	exportBoard.AddTask(model.NewTask("task-orig", "Task 1", model.StatusToDo))	exportBoard := model.NewBoard("original-id", "Imported Board")	// Create an export file manually	storage, _ := NewStorageWithPath(dir)	defer cleanup()	dir, cleanup := createTestDir(t)func TestImportBoard(t *testing.T) {}	}		t.Errorf("Expected 2 tasks, got %d", len(exported.Tasks))	if len(exported.Tasks) != 2 {	}		t.Error("Exported board ID mismatch")	if exported.ID != board.ID {	}		t.Fatalf("Failed to parse export file: %v", err)	if err := json.Unmarshal(data, &exported); err != nil {	var exported model.Board	}		t.Fatalf("Failed to read export file: %v", err)	if err != nil {	data, err := os.ReadFile(exportPath)	// Verify export file	}		t.Fatalf("ExportBoard failed: %v", err)	if err != nil {	err := storage.ExportBoard(board, exportPath)	exportPath := filepath.Join(dir, "export.json")	board.AddTask(model.NewTask("task-2", "Task 2", model.StatusInProgress))	board.AddTask(model.NewTask("task-1", "Task 1", model.StatusToDo))	board := model.NewBoard("test", "Test Board")	storage, _ := NewStorageWithPath(dir)	defer cleanup()	dir, cleanup := createTestDir(t)func TestExportBoard(t *testing.T) {// ============ Export/Import Tests (14.6 extended) ============}	}		t.Error("Empty archive should have no tasks")	if len(archive.Tasks) != 0 {	}		t.Fatalf("LoadArchive should not fail for non-existent: %v", err)	if err != nil {	archive, err := storage.LoadArchive("non-existent")	storage, _ := NewStorageWithPath(dir)	defer cleanup()	dir, cleanup := createTestDir(t)func TestLoadEmptyArchive(t *testing.T) {}	}		t.Errorf("Expected 2 archived tasks, got %d", len(archive.Tasks))	if len(archive.Tasks) != 2 {	archive, _ := storage.LoadArchive(board.ID)	}		t.Fatalf("ArchiveTasks failed: %v", err)	if err != nil {	err := storage.ArchiveTasks([]*model.Task{task1, task2}, board)	// Archive both tasks	storage.SaveBoard(board)	board.AddTask(task2)	board.AddTask(task1)	task2 := model.NewTask("task-2", "Task 2", model.StatusDone)	task1 := model.NewTask("task-1", "Task 1", model.StatusDone)	board := model.NewBoard("test", "Test Board")	storage, _ := NewStorageWithPath(dir)	defer cleanup()	dir, cleanup := createTestDir(t)func TestArchiveMultipleTasks(t *testing.T) {}	}		t.Error("ArchivedAt should be set")	if archive.Tasks[0].ArchivedAt.IsZero() {	}		t.Error("BoardID mismatch in archived task")	if archive.Tasks[0].BoardID != board.ID {	}		t.Error("Archived task ID mismatch")	if archive.Tasks[0].Task.ID != task.ID {	}		t.Errorf("Expected 1 archived task, got %d", len(archive.Tasks))	if len(archive.Tasks) != 1 {	}		t.Fatalf("LoadArchive failed: %v", err)	if err != nil {	archive, err := storage.LoadArchive(board.ID)	// Load archive and verify	}		t.Fatalf("ArchiveTask failed: %v", err)	if err != nil {	err := storage.ArchiveTask(task, board)	// Archive the task	storage.SaveBoard(board)	board.AddTask(task)	task := model.NewTask("task-1", "Task 1", model.StatusDone)	board := model.NewBoard("test", "Test Board")	storage, _ := NewStorageWithPath(dir)	defer cleanup()	dir, cleanup := createTestDir(t)func TestArchiveTask(t *testing.T) {// ============ Archive Tests (14.11) ============}	}		t.Error("Backup should be created before delete")	if len(entries) == 0 {	entries, _ := os.ReadDir(filepath.Join(dir, "backups"))	// Backup should exist	}		t.Error("Board should not exist after delete")	if err == nil {	_, err = storage.LoadBoard("test")	// Board should be gone	}		t.Fatalf("DeleteBoard failed: %v", err)	if err != nil {	err := storage.DeleteBoard("test")	// Delete board (should backup first)	storage.SaveBoard(board)	board := model.NewBoard("test", "Test Board")	storage, _ := NewStorageWithPath(dir)	defer cleanup()	dir, cleanup := createTestDir(t)func TestDeleteBoardCreatesBackup(t *testing.T) {}	}		t.Error("Backup file should exist")	if !found {	}		}			break			found = true		if filepath.Ext(entry.Name()) == ".json" {	for _, entry := range entries {	found := false	}		t.Fatalf("Failed to read backups dir: %v", err)	if err != nil {	entries, err := os.ReadDir(filepath.Join(dir, "backups"))	// Check backup file exists	}		t.Fatalf("BackupBoard failed: %v", err)	if err != nil {	err := storage.BackupBoard("test")	// Create backup	storage.SaveBoard(board)	board.AddTask(model.NewTask("task-1", "Task 1", model.StatusToDo))	board := model.NewBoard("test", "Test Board")	storage, _ := NewStorageWithPath(dir)	defer cleanup()	dir, cleanup := createTestDir(t)func TestBackupBoard(t *testing.T) {// ============ Backup Tests (14.10) ============}	}		}			t.Error("Temp file should not remain after save")		if filepath.Ext(entry.Name()) == ".tmp" {	for _, entry := range entries {	entries, _ := os.ReadDir(filepath.Join(dir, "data", "boards"))	// Verify no temp files remain after save	storage.SaveBoard(board)	board := model.NewBoard("test", "Test Board")	storage, _ := NewStorageWithPath(dir)	defer cleanup()	dir, cleanup := createTestDir(t)func TestAtomicWrite(t *testing.T) {}	}		t.Error("Loading corrupt board should return error")	if err == nil {	_, err := storage.LoadBoard("corrupt")	os.WriteFile(corruptPath, []byte("{ invalid json"), 0644)	corruptPath := filepath.Join(dir, "data", "boards", "board-corrupt.json")	// Write corrupt JSON	storage, _ := NewStorageWithPath(dir)	defer cleanup()	dir, cleanup := createTestDir(t)func TestLoadCorruptBoard(t *testing.T) {// ============ Error Handling Tests (14.9) ============}	}		t.Errorf("Expected most recent to be board-2, got %s", recent.ID)	if recent.ID != "board-2" {	}		t.Fatalf("MostRecentBoard failed: %v", err)	if err != nil {	recent, err := storage.MostRecentBoard()	storage.SaveBoard(board2) // This is saved later, so it's more recent	board2 := model.NewBoard("board-2", "Second Board")	storage.SaveBoard(board1)	board1 := model.NewBoard("board-1", "First Board")	// Create boards	}		t.Error("Expected nil when no boards exist")	if board != nil {	}		t.Fatalf("MostRecentBoard failed: %v", err)	if err != nil {	board, err := storage.MostRecentBoard()	// No boards returns nil	storage, _ := NewStorageWithPath(dir)	defer cleanup()	dir, cleanup := createTestDir(t)func TestMostRecentBoard(t *testing.T) {}	}		t.Errorf("board-2 should have 2 tasks, got %d", info.TaskCount)	} else if info.TaskCount != 2 {		t.Error("board-2 not found")	if info, ok := found["board-2"]; !ok {	}		t.Errorf("board-1 should have 1 task, got %d", info.TaskCount)	} else if info.TaskCount != 1 {		t.Error("board-1 not found")	if info, ok := found["board-1"]; !ok {	}		found[b.ID] = b	for _, b := range boards {	found := make(map[string]BoardInfo)	// Verify board info	}		t.Errorf("Expected 2 boards, got %d", len(boards))	if len(boards) != 2 {	}		t.Fatalf("ListBoards failed: %v", err)	if err != nil {	boards, err = storage.ListBoards()	storage.SaveBoard(board2)	board2.AddTask(model.NewTask("task-3", "Task 3", model.StatusInProgress))	board2.AddTask(model.NewTask("task-2", "Task 2", model.StatusToDo))	board2 := model.NewBoard("board-2", "Second Board")	storage.SaveBoard(board1)	board1.AddTask(model.NewTask("task-1", "Task 1", model.StatusToDo))	board1 := model.NewBoard("board-1", "First Board")	// Create some boards	}		t.Errorf("Expected 0 boards, got %d", len(boards))	if len(boards) != 0 {	}		t.Fatalf("ListBoards failed: %v", err)	if err != nil {	boards, err := storage.ListBoards()	// Empty list initially	storage, _ := NewStorageWithPath(dir)	defer cleanup()	dir, cleanup := createTestDir(t)func TestListBoards(t *testing.T) {// ============ ListBoards Tests (14.8) ============}	}		t.Error("Loading non-existent board should return error")	if err == nil {	_, err := storage.LoadBoard("non-existent")	storage, _ := NewStorageWithPath(dir)	defer cleanup()	dir, cleanup := createTestDir(t)func TestLoadNonExistentBoard(t *testing.T) {}	}		t.Errorf("Task Labels mismatch")	if len(loadedTask.Labels) != len(task.Labels) {	}		t.Errorf("Task Priority mismatch")	if loadedTask.Priority != task.Priority {	}		t.Errorf("Task Title mismatch")	if loadedTask.Title != task.Title {	}		t.Errorf("Task ID mismatch")	if loadedTask.ID != task.ID {	loadedTask := loaded.Tasks[0]	}		t.Fatalf("Task count mismatch: expected 1, got %d", len(loaded.Tasks))	if len(loaded.Tasks) != 1 {	}		t.Errorf("Name mismatch: expected %s, got %s", board.Name, loaded.Name)	if loaded.Name != board.Name {	}		t.Errorf("ID mismatch: expected %s, got %s", board.ID, loaded.ID)	if loaded.ID != board.ID {	// Verify loaded data	}		t.Fatalf("Failed to load board: %v", err)	if err != nil {	loaded, err := storage.LoadBoard("test-board")	// Load the board back	}		t.Fatalf("Failed to save board: %v", err)	if err := storage.SaveBoard(board); err != nil {	// Save the board	board.AddTask(task)	task.Labels = []string{"bug", "urgent"}	task.Priority = model.PriorityHigh	task.Description = "A test description"	task := model.NewTask("task-1", "Test Task", model.StatusToDo)	board := model.NewBoard("test-board", "Test Board")	// Create a board	}		t.Fatalf("Failed to create storage: %v", err)	if err != nil {	storage, err := NewStorageWithPath(dir)	defer cleanup()	dir, cleanup := createTestDir(t)func TestSaveAndLoadBoard(t *testing.T) {// ============ Load/Save Tests (14.6-14.7) ============}	_ = storage // Use the storage	}		t.Error("Backups directory should be created")	if _, err := os.Stat(backupsDir); os.IsNotExist(err) {	backupsDir := filepath.Join(dir, "backups")	}		t.Error("Boards directory should be created")	if _, err := os.Stat(boardsDir); os.IsNotExist(err) {	boardsDir := filepath.Join(dir, "data", "boards")	// Check directories were created	}		t.Fatalf("Failed to create storage: %v", err)	if err != nil {	storage, err := NewStorageWithPath(dir)	defer cleanup()	dir, cleanup := createTestDir(t)func TestNewStorageWithPath(t *testing.T) {// ============ Storage Creation Tests (14.6) ============}	return dir, func() { os.RemoveAll(dir) }	}		t.Fatalf("Failed to create temp dir: %v", err)	if err != nil {	dir, err := os.MkdirTemp("", "tsk-test-*")	t.Helper()func createTestDir(t *testing.T) (string, func()) {// Helper function to create a temp directory for tests)	"github.com/coliva/tsk/internal/model"	"testing"	"path/filepath"	"os"